# Ficha de trabalho 4

1- Considera o dataset cachexia. Lê os dados usando a função read_csv do pandas (dados e metadados).

In [11]:
import pandas as pd
data_metlab = pd.read_csv(r'C:\Users\Tiago\GitHub\Repositorio de Sistemas\Repositorio-Sistemas\datasets\data_cachexia.csv',sep=',', index_col = 0)
meta_metlab = pd.read_csv(r'C:\Users\Tiago\GitHub\Repositorio de Sistemas\Repositorio-Sistemas\datasets\meta_cachexia.csv',sep=',', index_col = 0)
print(data_metlab.shape)
print(meta_metlab.shape)


(77, 63)
(77, 1)


2 -Aplica a transformação necessária para que os dados seja escalonados para ter média 0 e desvio padrão 1. Verifica que as médias de todas as colunas é aproximadamente zero.

In [3]:
from sklearn import preprocessing
input_data = data_metlab.values
output_data = meta_metlab.values[:,0]

input_sc = preprocessing.scale(input_data) #media 0 e desvio padrao = 1

print("Media global: ", input_sc.mean())
print("Desvio padrao global: ", input_sc.std())

Media global:  -1.8675365658506033e-17
Desvio padrao global:  1.0


3 - Cria dois conjuntos de dados treino e teste para serem usados na criação e validação de modelos de aprendizagem máquina. Considera 30% das amostras para formar o conjunto de teste. 

In [6]:
import numpy as np

numts = int(len(input_sc)*0.3)

indices = np.random.permutation(len(input_sc))

train_in = input_sc[indices[:-numts]]
train_out = output_data[indices[:-numts]]

test_in = input_sc[indices[-numts:]]
test_out = output_data[indices[-numts:]]

4 - Constroi diversos tipos de modelos de classificação treinando e testando com os conjuntos criados anteriormente. Calcula, para cada um dos modelos no test set, as métricas de erro PECC e F1-score, e calcula a matriz de confusão. Considere como classe positiva a classe "cachexic"

In [30]:
#Knn
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()
knn.fit(train_in, train_out)
prev = knn.predict(test_in)

print("Accuracy:",knn.score(test_in, test_out))

Accuracy: 0.6086956521739131


In [31]:
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

print("PECC: ", accuracy_score(test_out, prev))
print("F1_score: ", f1_score(test_out, prev, pos_label= "cachexic"))
print("Confusion Matrix:\n", confusion_matrix(test_out, prev))

PECC:  0.6086956521739131
F1_score:  0.6896551724137931
Confusion Matrix:
 [[10  3]
 [ 6  4]]


In [32]:
tn, fp, fn, tp = confusion_matrix(test_out, prev).ravel()
print("VP: ", tp)
print("VN: ", tn)
print("FP: ", fp)
print("FN: ", fn)

VP:  4
VN:  10
FP:  3
FN:  6


In [33]:
#Arvore de decisão
from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier()
tree.fit(train_in, train_out)
prev = tree.predict(test_in)
print("PECC: ", accuracy_score(test_out, prev))
print("F1_score: ", f1_score(test_out, prev, pos_label= "cachexic"))
print("Confusion Matrix:\n", confusion_matrix(test_out, prev))

PECC:  0.782608695652174
F1_score:  0.8387096774193548
Confusion Matrix:
 [[13  0]
 [ 5  5]]


In [34]:
from matplotlib import test
from sklearn.naive_bayes import GaussianNB

gaussian = GaussianNB()
gaussian.fit(train_in, train_out)
prev = gaussian.predict(test_in)
print("PECC: ", accuracy_score(test_out, prev))
print("F1_score: ", f1_score(test_out, prev, pos_label= "cachexic"))
print("Confusion Matrix:\n", confusion_matrix(test_out, prev))

PECC:  0.8695652173913043
F1_score:  0.888888888888889
Confusion Matrix:
 [[12  1]
 [ 2  8]]


5 - Usando apenas o melhor modelo do exercício anterior, compare o seu desempenho considerando dados com transformação logaritmica e posteriormente standardizados

In [35]:
input_log = np.log2(input_data)
input_log_sc = preprocessing.scale(input_log)

train_in_log = input_log_sc[indices[:-numts]]
test_in_log = input_log_sc[indices[-numts:]]

gaussian = GaussianNB()
gaussian.fit(train_in_log, train_out)
prev = gaussian.predict(test_in_log)
print("PECC: ", accuracy_score(test_out, prev))
print("F1_score: ", f1_score(test_out, prev, pos_label= "cachexic"))
print("Confusion Matrix:\n", confusion_matrix(test_out, prev))

PECC:  0.8695652173913043
F1_score:  0.888888888888889
Confusion Matrix:
 [[12  1]
 [ 2  8]]
